In [1]:
import test_bool
import numpy as np

arr = np.zeros(5, dtype = np.uint8)
arr[0] = 1
res = test_bool.test_bool(arr)

ModuleNotFoundError: No module named 'test_bool'

In [2]:
import solve_shadow_map
import numpy as np

ray_point = np.array([[5, 5, 5.4], [5, 4, 4.4]], dtype = np.float32)
ray_vec = np.array([[0.0, 0.0, -1], [0.0, 0.0, -1]], dtype = np.float32)
minBound = np.array([0, 0, 0], dtype = np.float32)
maxBound = np.array([10, 10, 10], dtype = np.float32)
terrain_voxel_map = np.zeros([10, 10, 10], dtype = np.uint8)
terrain_voxel_map[:, :, 0] = 1
terrain_voxel_map[:, :, 1] = 1

res = solve_shadow_map.solve_shadow_map_cy(ray_point, ray_vec, minBound, maxBound, terrain_voxel_map)
print(res)

[5 5 5]
[5 5 4]
[5 5 3]
[5 5 2]
[5 4 4]
[5 4 3]
[5 4 2]
[5 5 5]
[5 5 4]
[5 5 3]
[5 5 2]
[5 4 4]
[5 4 3]
[5 4 2]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


/tmp/ipykernel_4761/826828556.py:12: RuntimeWarning: divide by zero encountered in divide
  res = solve_shadow_map.solve_shadow_map_cy(ray_point, ray_vec, minBound, maxBound, terrain_voxel_map)
